// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 



class DefaultFirebaseOptions {
  
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB377d4_AFRtoEIjpN2Puf3CYwe-I9dCGE',
    appId: '1:711189707453:web:e74dd4a2a8c2c4b00b55d4',
    messagingSenderId: '711189707453',
    projectId: 'vff-group-b185c',
    authDomain: 'vff-group-b185c.firebaseapp.com',
    storageBucket: 'vff-group-b185c.appspot.com',
    measurementId: 'G-RWGD4RD6R8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiF4DzKdOcMR3uI8-QQtS-DAtCLclmr3M',
    appId: '1:711189707453:android:d9df1c9a43057bb40b55d4',
    messagingSenderId: '711189707453',
    projectId: 'vff-group-b185c',
    storageBucket: 'vff-group-b185c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmfHt785AG0SmotAGJTkeyU6jsaedkafM',
    appId: '1:711189707453:ios:c04d656ccc9448110b55d4',
    messagingSenderId: '711189707453',
    projectId: 'vff-group-b185c',
    storageBucket: 'vff-group-b185c.appspot.com',
    iosBundleId: 'com.vffgroup.vffgroup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmfHt785AG0SmotAGJTkeyU6jsaedkafM',
    appId: '1:711189707453:ios:132aaaa7eb00f4490b55d4',
    messagingSenderId: '711189707453',
    projectId: 'vff-group-b185c',
    storageBucket: 'vff-group-b185c.appspot.com',
    iosBundleId: 'com.example.vffGroup.RunnerTests',
  );
}


